=== NatholDallas/natools4jk/src/main/resources/card.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="theme">
        <xs:restriction base="xs:string">
            <xs:enumeration value="primary" />
            <xs:enumeration value="success" />
            <xs:enumeration value="danger" />
            <xs:enumeration value="warning" />
            <xs:enumeration value="info" />
            <xs:enumeration value="secondary" />
            <xs:enumeration value="none" />
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="size">
        <xs:restriction base="xs:string">
            <xs:enumeration value="lg" />
            <xs:enumeration value="sm" />
            <xs:enumeration value="xs" />
            <xs:enumeration value="md" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MarkdownElement">
        <xs:restriction base="xs:string" />
    </xs:simpleType>


    <xs:simpleType name="PlainTextElement">
        <xs:restriction base="xs:string" />
    </xs:simpleType>


    <xs:complexType name="ImageElement">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="src" type="xs:string" />
            <xs:element name="alt" type="xs:string" />
            <xs:element name="size" type="size" />
            <xs:element name="circle" type="xs:boolean" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="ButtonElement">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="theme" type="theme" />
            <xs:element name="value" type="xs:string" />
            <xs:element name="eventType">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="NO_ACTION" />
                        <xs:enumeration value="LINK" />
                        <xs:enumeration value="RETURN_VAL" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="Paragraph">
        <xs:sequence>
            <xs:element name="columns" type="xs:int" />
            <xs:choice>
                <xs:element name="PlainTextElement" type="PlainTextElement" />
                <xs:element name="MarkdownElement" type="MarkdownElement" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="Accessory">
        <xs:choice>
            <xs:element name="ButtonElement" type="ButtonElement" />
            <xs:element name="ImageElement" type="ImageElement" />
        </xs:choice>
    </xs:complexType>


    <xs:complexType name="card">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ActionGroupModule">
                <xs:complexType>
                    <xs:choice minOccurs="1" maxOccurs="4">
                        <xs:element name="ButtonElement" type="ButtonElement" />
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="ContainerModule">
                <xs:complexType>
                    <xs:choice minOccurs="1" maxOccurs="9">
                        <xs:element name="ImageElement" type="ImageElement" />
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="ContextModule">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="PlainTextElement" type="PlainTextElement" />
                        <xs:element name="MarkdownElement" type="MarkdownElement" />
                        <xs:element name="ImageElement" type="ImageElement" />
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="CountdownModule">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="type">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="day" />
                                    <xs:enumeration value="hour" />
                                    <xs:enumeration value="second" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="endTime" type="xs:long" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DividerModule" />
            <xs:element name="FileModule">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="type">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="file" />
                                    <xs:enumeration value="audio" />
                                    <xs:enumeration value="video" />
                                    <xs:enumeration value="image" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="src" type="xs:string" />
                        <xs:element name="title" type="xs:string" />
                        <xs:element name="cover" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="HeaderModule" type="xs:string" />
            <xs:element name="ImageGroupModule">
                <xs:complexType>
                    <xs:choice minOccurs="1" maxOccurs="9">
                        <xs:element name="ImageElement" type="ImageElement" />
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="InviteModule" type="xs:string" />
            <xs:element name="SectionModule">
                <xs:complexType>
                    <xs:sequence>
                        <xs:choice>
                            <xs:element name="MarkdownElement" type="MarkdownElement" />
                            <xs:element name="PlainTextElement" type="PlainTextElement" />
                            <xs:element name="Paragraph" type="Paragraph" />
                        </xs:choice>
                        <xs:element name="Accessory" type="Accessory" />
                        <xs:element name="Mode">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="left" />
                                    <xs:enumeration value="right" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:choice>
        <xs:attribute name="theme" type="theme" use="required" />
        <xs:attribute name="size" type="size" use="required" />
    </xs:complexType>

    <xs:element name="building">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="card" type="card" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NatholDallas/natools4jk/src/main/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<building xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="card.xsd">
    <card theme="primary" size="lg">
        <ActionGroupModule>
            <InteractElementList>
                <ButtonElement>
                    <theme>primary</theme>
                    <value></value>
                    <eventType>NO_ACTION</eventType>
                </ButtonElement>
            </InteractElementList>
        </ActionGroupModule>
        <ContainerModule>
            <ImageElement>
                <src></src>
                <alt></alt>
                <size>lg</size>
                <circle>true</circle>
            </ImageElement>
        </ContainerModule>
        <ContextModule>
            <MarkdownElement></MarkdownElement>
        </ContextModule>
        <CountdownModule>
            <type>day</type>
            <endTime>1000</endTime>
        </CountdownModule>
        <DividerModule/>
        <FileModule>
            <type>file</type>
            <src></src>
            <title></title>
            <cover></cover>
        </FileModule>
        <HeaderModule>
            hello world
        </HeaderModule>
        <ImageGroupModule>
            <ImageElement>
                <src></src>
                <alt></alt>
                <size>lg</size>
                <circle>true</circle>
            </ImageElement>
        </ImageGroupModule>
        <InviteModule>
            code
        </InviteModule>
    </card>
    <card theme="primary" size="lg"></card>
</building>
